#!/usr/bin/python
import fire
import os
import xmltodict


class VM(object):
    def __init__(self, title, name, uuid, files):
        self.title = title
        self.name = name
        self.uuid = uuid
        self.files = files


class VirtManager(object):
    """A tool to handle GNOME Boxes and other libvirt software."""

    def __find(self, qemuDir, entry):
        with open(os.path.join(qemuDir,  entry), 'r') as handle:
            doc = xmltodict.parse(handle.read())
            domain = doc['domain']
            files = list()
            osinfo = domain["os"]
            if osinfo.has_key('loader'):
                files.append(osinfo["loader"]["#text"])
            if osinfo.has_key('nvram'):
                files.append(osinfo["nvram"])
            devices = domain["devices"]
            disks = devices["disk"]
            for disk in disks:
                src = disk["source"]
                if src.has_key('@startupPolicy'):
                    policy = src['@startupPolicy']
                    if policy == 'optional':
                        continue
                files.append(src["@file"])
            return VM(domain["title"], domain["name"], domain["uuid"], files)

    def list(self):
        homeDir = os.environ['HOME']
        virtDir = os.path.join(homeDir, ".config", "libvirt")
        qemuDir = os.path.join(virtDir, "qemu")
        for entry in os.listdir(qemuDir):
            if entry.endswith('.xml'):
                vm = self.__find(qemuDir, entry)
                print ' * ' + vm.title + ' (' + vm.name + ') [' + vm.uuid + ']'
                for file in vm.files:
                    print '    * ' + file

    def backup(self, to):
        if not os.path.exists(to):
            os.mkdir(to)
        print to


if __name__ == '__main__':
    fire.Fire(VirtManager)
